version: "3.8"

services:
  pgprimary:
    container_name: base_postgres
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - base_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_REPLICATION_MODE=master
      - POSTGRES_REPLICATION_USER=postgres
      - POSTGRES_REPLICATION_PASSWORD=1
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=test_db

volumes:
  base_data:
    external: true
    name: base_data
